version: '3'

services:

  game_poll_dev:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: game_poll_dev
    container_name: game_poll_dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - game_poll_db_dev
    links:
      - game_poll_db_dev

    restart: unless-stopped

  game_poll_db_dev:
    image: mongo:4.2.0
    container_name: game_poll_db_dev
    restart: unless-stopped
